feat: multiselect first draft
weweb-assets/ww-input-multiselect pull request #1
Opened 2022-03-04 10:43 UTC by AlexisJC

2022-03-04 17:25 UTC, AurelieV commented on package.json
> +    "@vueform/multiselect": "^2.3.3"
on devrait peut être fixer la version ici?

2022-03-04 17:25 UTC, AurelieV commented on src/wwElement.vue
> +        <span class="multiselect-tag" :style="option.style">{{ option.label }}</span>
pourquoi ne pas utiliser un ww-text ici? Cela permettrait de gérer la couleur du texte etc

2022-03-04 17:25 UTC, AurelieV commented on src/wwElement.vue
> +        return this.currentSelection
il faudrait gérer ici le cas ou on ne recoit pas de tableau

2022-03-04 17:25 UTC, AurelieV commented on src/wwElement.vue
> +      if (false === Array.isArray(this.content.options)) return []
!Array.isArray ?

2022-03-04 17:25 UTC, AurelieV commented on src/wwElement.vue
> +        } : { // to allow flat array
:)

2022-03-04 17:25 UTC, AurelieV commented on ww-config.js
> +            fr: "Saisie Multiselect",
Saisie multiple?

2022-03-04 17:25 UTC, AurelieV commented on ww-config.js
> +        enabled: {
sur tout nos autres input on a plutôt un champs disabled no?

2022-03-04 17:25 UTC, AurelieV commented on ww-config.js
> +            hidden: (content, sidepanelContent, boundProps) => !boundProps.options,
je ne sais pas à quel point ça va être chiant de formater la data sur le type attendu.

2022-03-07 08:07 UTC, AlexisJC commented on src/wwElement.vue
> +        <span class="multiselect-tag" :style="option.style">{{ option.label }}</span>
Je ne savais juste pas qu'on pouvait 💡

2022-03-07 08:09 UTC, AlexisJC commented on src/wwElement.vue
> +      if (false === Array.isArray(this.content.options)) return []
Petite habitude prise quand je faisais du back php, je trouve ça plus lisible que le point d'exclamation qu'on voit pas toujours au survol mais je vais changer

2022-03-07 18:30 UTC, Dams-d requested changes

2022-03-07 18:30 UTC, Dams-d commented on package.json
> +  "version": "0.1.0",
version 3.1.0 pour etre consistant

2022-03-07 18:30 UTC, Dams-d commented on src/wwElement.vue
> +  &.editing {
Tu peux /* wwEditor:start */ ca je pense

2022-03-07 18:32 UTC, AurelieV commented on src/wwElement.vue
> +        <span class="multiselect-tag" :style="option.style">{{ option.label }}</span>
On peut tout faire :p

2022-03-08 08:39 UTC, AlexisJC commented on ww-config.js
> +            hidden: (content, sidepanelContent, boundProps) => !boundProps.options,
Je vois pas comment faire perso, mais quand je l'ai mentionné on m'a dit que ça viendrait avec les Iterators

2022-03-08 08:40 UTC, AlexisJC commented on ww-config.js
> +        enabled: {
Je trouvais ça génant sur le moment d'avoir un OnOff où desabled serait ON et enabled serait OFF, mais si c'est un pattern commun pas de soucis je change

2022-03-08 08:44 UTC, AlexisJC commented on src/wwElement.vue
> +        return this.currentSelection
C'est géré à l'init de currentSelection ligne 53, tu as forcément un tableau

2022-03-08 08:49 UTC, AurelieV commented on ww-config.js
> +            hidden: (content, sidepanelContent, boundProps) => !boundProps.options,
Les iterator ca sera pour les workflow pas les formules. Mais vu avec flo go la dessus et on y reviendra plus tard

2022-03-08 10:40 UTC, AlexisJC commented on src/wwElement.vue
> +        <span class="multiselect-tag" :style="option.style">{{ option.label }}</span>
Ah non mais t'as pas du faire attention, c'est un slot du multiselect qui est répété autant de fois qu'on a d'options dans le select, ton idée de ww-text c'est quand tu as un texte fixe non ? Genre un titre ou un message unique.

2022-03-08 10:41 UTC, AlexisJC commented on src/wwElement.vue
> +        return this.currentSelection
J'ai géré à l'init de la variable currentSelection et dans le watch de internalValue

2022-03-08 11:01 UTC, AurelieV commented on src/wwElement.vue
> +        return this.currentSelection
Si on doit préparer le set depuis l'extérieur, on va être obligé de faire attention à ça, tu peux rechech que ça ne pose pas de souci?

2022-03-08 11:02 UTC, AurelieV commented on src/wwElement.vue
> +        <span class="multiselect-tag" :style="option.style">{{ option.label }}</span>
Tu peux avoir un objet ww-text (uid) qui est le même pour tous, mais qui a une instance pour chaque repeat, avec un texte forcé via wwProps unique à chaque instance. Quand tu modifieras la police de l'un, ça les modifiera tous :).

2022-03-11 14:06 UTC, Kramerbaf approved these changes

2022-03-11 14:07 UTC, merged