Scoped css
weweb-assets/ww-input-multiselect pull request #20
Opened 2022-09-14 14:23 UTC by AurelieV

2022-09-15 09:04 UTC, AlexisJC requested changes

2022-09-15 09:04 UTC, AlexisJC commented on src/wwElement.vue
> +                debugger;
T'as oublié le debugger :D

2022-09-15 09:05 UTC, AurelieV commented on src/wwElement.vue
> +                debugger;
arf ça devait dater d'avant pour un autre bug, fixed

2022-09-15 09:36 UTC, AlexisJC approved these changes

2022-09-20 10:12 UTC, Kramerbaf approved these changes

2022-09-20 12:03 UTC, merged