Add property for font size of search
weweb-assets/ww-input-multiselect pull request #40
Opened 2023-02-28 10:23 UTC by AurelieV

2023-03-07 10:34 UTC, kevinbarfleur approved these changes

2023-03-07 11:13 UTC, AlexisJC approved these changes

2023-03-08 09:25 UTC, MarcFabre requested changes

2023-03-08 09:25 UTC, MarcFabre commented on src/wwElement.vue
> +    font-size: var(--search-font-size);
Pas de font-family ni color ici ?

2023-03-08 09:34 UTC, AurelieV commented on src/wwElement.vue
> +    font-size: var(--search-font-size);
Encore un oubli de push sorry

2023-03-08 17:29 UTC, merged