WW-2577 Reset advanced options
weweb-assets/ww-input-multiselect pull request #74
Opened 2024-05-02 10:17 UTC by kevinbarfleur

2024-05-16 11:56 UTC, MarcFabre approved these changes

2024-05-16 11:57 UTC, MarcFabre requested changes
En fait ça ne va pas marcher en prod parce qu'on ne peut pas updateEffect dans le site publié. Je me trompe @AurelieV  ?

2024-05-16 11:58 UTC, AurelieV commented
> En fait ça ne va pas marcher en prod parce qu'on ne peut pas updateEffect dans le site publié. Je me trompe @AurelieV ?

Oui on ne peut pas update tout court (effect ou pas) car ça modifie la DB

2024-05-16 12:00 UTC, MarcFabre commented
@kevinbarfleur en fait il faut que tu change la logique pour avoir les props "advanced" en computed qui dépendent de content.advanced

2024-05-22 07:10 UTC, MarcFabre approved these changes

2024-05-23 07:05 UTC, merged